/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import modelo.ProductoDAO;
import modelo.producto;

/**
 *
 * @author Enrique Isales
 */
public class ProductosForm extends javax.swing.JInternalFrame {
        ProductoDAO dao1 = new ProductoDAO();
        producto cl = new producto();
    
    
        DefaultTableModel modelo= new DefaultTableModel();
        int id;
    
    
    
    
    
    public ProductosForm() {
        initComponents();
        listar();
    }

    void listar() {
        List<producto> lista = dao1.listar();
        modelo = (DefaultTableModel) tablaP.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getId();
            ob[1] = lista.get(i).getNomP();
            ob[2] = lista.get(i).getPrecioP();
            ob[3] = lista.get(i).getStockP();
            ob[4] = lista.get(i).getEstadoP();
            modelo.addRow(ob);

        }
        tablaP.setModel(modelo);
    }
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtstockP = new javax.swing.JTextField();
        txtnomP = new javax.swing.JTextField();
        txtprecioP = new javax.swing.JTextField();
        comboEstadoP = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnagregarP = new javax.swing.JButton();
        btnactualizarP = new javax.swing.JButton();
        btneliminarP = new javax.swing.JButton();
        btnnuevoP = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaP = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Menu de Productos");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 75, 60));
        jLabel1.setText("NOMBRE:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 76, 60));
        jLabel2.setText("PRECIO:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 76, 60));
        jLabel3.setText("STOCK");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 76, 60));
        jLabel4.setText("ESTADO:");

        txtstockP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtnomP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtprecioP.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        comboEstadoP.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboEstadoP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "0", "1" }));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(231, 76, 60))); // NOI18N

        btnagregarP.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnagregarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-agregar-base-de-datos-32.png"))); // NOI18N
        btnagregarP.setText("AGREGAR");
        btnagregarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarPActionPerformed(evt);
            }
        });

        btnactualizarP.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnactualizarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-actualizar-32.png"))); // NOI18N
        btnactualizarP.setText("ACTUALIZAR");
        btnactualizarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarPActionPerformed(evt);
            }
        });

        btneliminarP.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btneliminarP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-32.png"))); // NOI18N
        btneliminarP.setText("ELIMINAR");
        btneliminarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarPActionPerformed(evt);
            }
        });

        btnnuevoP.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnnuevoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-crear-nuevo-32.png"))); // NOI18N
        btnnuevoP.setText("NUEVO");
        btnnuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnagregarP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizarP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminarP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnomP, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(txtstockP)
                            .addComponent(txtprecioP, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(comboEstadoP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtnomP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtprecioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtstockP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboEstadoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "NOMBRE DEL PRODUCTO", "PRECIO", "STOCK", "ESTADO"
            }
        ));
        tablaP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaP);
        if (tablaP.getColumnModel().getColumnCount() > 0) {
            tablaP.getColumnModel().getColumn(0).setMaxWidth(80);
            tablaP.getColumnModel().getColumn(2).setMaxWidth(100);
            tablaP.getColumnModel().getColumn(3).setMaxWidth(100);
            tablaP.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarPActionPerformed

        agregar();
        limpiarTabla();
        listar();
        nuevo();

    }//GEN-LAST:event_btnagregarPActionPerformed

    private void btnactualizarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarPActionPerformed

        actualizar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btnactualizarPActionPerformed

    private void btneliminarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarPActionPerformed
        eliminar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btneliminarPActionPerformed

    private void btnnuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoPActionPerformed
        nuevo();
        limpiarTabla();
    }//GEN-LAST:event_btnnuevoPActionPerformed

    private void tablaPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPMouseClicked

        int fila=tablaP.getSelectedRow();

        if(fila == -1){
            JOptionPane.showMessageDialog(this,"Debe Seleccionar una Fila");
        }else{
            id= Integer.parseInt(tablaP.getValueAt(fila, 0).toString());
            String nom=tablaP.getValueAt(fila, 1).toString();
            String precio=tablaP.getValueAt(fila, 2).toString();
            String Stock=tablaP.getValueAt(fila, 3).toString();
            String estado=tablaP.getValueAt(fila, 4).toString();
            txtnomP.setText(nom);
            txtprecioP.setText(precio);
            txtstockP.setText(Stock);
            comboEstadoP.setSelectedItem(estado);
        }

    }//GEN-LAST:event_tablaPMouseClicked

     void agregar() {
        String nomP = txtnomP.getText();
        String precioP = txtprecioP.getText();
        String stockP = txtstockP.getText();
        String esP = comboEstadoP.getSelectedItem().toString();

        Object[] ob1 = new Object[4];
        ob1[0] = nomP;
        ob1[1] = precioP;
        ob1[2] = stockP;
        ob1[3] = esP;
        dao1.add(ob1);

    }

    void actualizar() {
        int fila = tablaP.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar una fila");

        } else {

            String nomP = txtnomP.getText();
            String precioP = txtprecioP.getText();
            String stockP = txtstockP.getText();
            String esP = comboEstadoP.getSelectedItem().toString();

            Object[] obj1 = new Object[5];

            obj1[0] = nomP;
            obj1[1] = precioP;
            obj1[2] = stockP;
            obj1[3] = esP;
            obj1[4] = id;
            dao1.actualizar(obj1);

        }

    }

    void eliminar() {
        int fila = tablaP.getSelectedRow();
        int ids = Integer.parseInt(tablaP.getValueAt(fila, 0).toString());
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar una fila");

        } else {

            dao1.eliminar(ids);
        }

    }

    void nuevo() {
        txtnomP.setText("");
        txtprecioP.setText("");
        txtstockP.setText("");
        comboEstadoP.setSelectedItem(0);
        txtnomP.requestFocus();

    }

    void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;

        }
    }

    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizarP;
    private javax.swing.JButton btnagregarP;
    private javax.swing.JButton btneliminarP;
    private javax.swing.JButton btnnuevoP;
    private javax.swing.JComboBox<String> comboEstadoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaP;
    private javax.swing.JTextField txtnomP;
    private javax.swing.JTextField txtprecioP;
    private javax.swing.JTextField txtstockP;
    // End of variables declaration//GEN-END:variables
}
