/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Vendedor;
import modelo.VendedorDAO;



/**
 *
 * @author Enrique Isales
 */
public class VendedorForm extends javax.swing.JInternalFrame {
        VendedorDAO dao1 = new VendedorDAO();
        Vendedor cl = new Vendedor();
    
    
        DefaultTableModel modelo= new DefaultTableModel();
        int id;
    
    
    

    
    public VendedorForm() {
        initComponents();
        listar();
    }
    
    
    
    void listar() {
        List<Vendedor> lista = dao1.listar();
        modelo = (DefaultTableModel) tablaV.getModel();
        Object[] ob = new Object[6];
        for (int i = 0; i < lista.size(); i++) {
            ob[0] = lista.get(i).getId();
            ob[1] = lista.get(i).getDpi();
            ob[2] = lista.get(i).getNom();
            ob[3] = lista.get(i).getTel();
            ob[4] = lista.get(i).getEstado();
            ob[5] = lista.get(i).getUsua2();
            
            modelo.addRow(ob);

        }
        tablaV.setModel(modelo);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTelV = new javax.swing.JTextField();
        txtdpiV = new javax.swing.JTextField();
        txtnombresV = new javax.swing.JTextField();
        comboEstadoV = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        btnagregarV = new javax.swing.JButton();
        btnactualizarV = new javax.swing.JButton();
        btneliminarV = new javax.swing.JButton();
        btnnuevoV = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtusu2 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaV = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setTitle("Menu de Vendedores");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(231, 76, 60));
        jLabel1.setText("DPI:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(231, 76, 60));
        jLabel2.setText("NOMBRES:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(231, 76, 60));
        jLabel3.setText("TELEFONO:");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(231, 76, 60));
        jLabel4.setText("ESTADO:");

        txtTelV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtdpiV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        txtnombresV.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        comboEstadoV.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        comboEstadoV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "0", "1" }));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OPCIONES", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 3, 14), new java.awt.Color(231, 76, 60))); // NOI18N

        btnagregarV.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnagregarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-agregar-base-de-datos-32.png"))); // NOI18N
        btnagregarV.setText("AGREGAR");
        btnagregarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarVActionPerformed(evt);
            }
        });

        btnactualizarV.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnactualizarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-actualizar-32.png"))); // NOI18N
        btnactualizarV.setText("ACTUALIZAR");
        btnactualizarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarVActionPerformed(evt);
            }
        });

        btneliminarV.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btneliminarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-eliminar-32.png"))); // NOI18N
        btneliminarV.setText("ELIMINAR");
        btneliminarV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarVActionPerformed(evt);
            }
        });

        btnnuevoV.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        btnnuevoV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-crear-nuevo-32.png"))); // NOI18N
        btnnuevoV.setText("NUEVO");
        btnnuevoV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnuevoV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneliminarV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnactualizarV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnagregarV, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnagregarV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnactualizarV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btneliminarV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnnuevoV, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(231, 76, 60));
        jLabel5.setText("USUARIO:");

        txtusu2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdpiV)
                            .addComponent(txtTelV)
                            .addComponent(txtnombresV)
                            .addComponent(comboEstadoV, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusu2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtdpiV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtnombresV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTelV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(comboEstadoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtusu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tablaV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "DPI", "NOMBRES", "TELEFONO", "ESTADO", "USUARIO"
            }
        ));
        tablaV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaV);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarVActionPerformed
        agregar();
        limpiarTabla();
        listar();
        nuevo();

    }//GEN-LAST:event_btnagregarVActionPerformed

    private void btnactualizarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarVActionPerformed

        actualizar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btnactualizarVActionPerformed

    private void btneliminarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarVActionPerformed
        eliminar();
        limpiarTabla();
        listar();
        nuevo();
    }//GEN-LAST:event_btneliminarVActionPerformed

    private void btnnuevoVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoVActionPerformed
        nuevo();
        limpiarTabla();
    }//GEN-LAST:event_btnnuevoVActionPerformed

    private void tablaVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVMouseClicked

        int fila=tablaV.getSelectedRow();

        if(fila == -1){
            JOptionPane.showMessageDialog(this,"Debe Seleccionar una Fila");
        }else{
            id= Integer.parseInt(tablaV.getValueAt(fila, 0).toString());
            String dpi=tablaV.getValueAt(fila, 1).toString();
            String nom=tablaV.getValueAt(fila, 2).toString();
            String tel=tablaV.getValueAt(fila, 3).toString();
            String es=tablaV.getValueAt(fila, 4).toString();
            String usu=tablaV.getValueAt(fila, 5).toString();
            txtdpiV.setText(dpi);
            txtnombresV.setText(nom);
            txtTelV.setText(tel);
            comboEstadoV.setSelectedItem(es);
            txtusu2.setText(usu);
        }

    }//GEN-LAST:event_tablaVMouseClicked

    void agregar() {
        String dpi = txtdpiV.getText();
        String nom = txtnombresV.getText();
        String tel = txtTelV.getText();
        String es = comboEstadoV.getSelectedItem().toString();
        String usuu = txtusu2.getText();

        Object[] ob1 = new Object[5];
        ob1[0] = dpi;
        ob1[1] = nom;
        ob1[2] = tel;
        ob1[3] = es;
        ob1[4] = usuu;
        dao1.add(ob1);

    }

    void actualizar() {
        int fila = tablaV.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar una fila");

        } else {

            String dpi = txtdpiV.getText();
            String nom = txtnombresV.getText();
            String tel = txtTelV.getText();
            String es = comboEstadoV.getSelectedItem().toString();
            String usuu = txtusu2.getText();

            Object[] obj1 = new Object[6];

            obj1[0] = dpi;
            obj1[1] = nom;
            obj1[2] = tel;
            obj1[3] = es;
            obj1[4] = usuu;
            obj1[5] = id;
            dao1.actualizar(obj1);

        }

    }

    void eliminar() {
        int fila = tablaV.getSelectedRow();
        int ids = Integer.parseInt(tablaV.getValueAt(fila, 0).toString());
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debe Ingresar una fila");

        } else {

            dao1.eliminar(ids);
        }

    }

    void nuevo() {
       
            txtdpiV.setText("");
            txtnombresV.setText("");
            txtTelV.setText("");
            comboEstadoV.setSelectedItem(0);
            txtusu2.setText("");
            txtdpiV.requestFocus();

    }

    void limpiarTabla() {
        for (int i = 0; i < modelo.getRowCount(); i++) {
            modelo.removeRow(i);
            i = i - 1;

        }
    }
    
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizarV;
    private javax.swing.JButton btnagregarV;
    private javax.swing.JButton btneliminarV;
    private javax.swing.JButton btnnuevoV;
    private javax.swing.JComboBox<String> comboEstadoV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaV;
    private javax.swing.JTextField txtTelV;
    private javax.swing.JTextField txtdpiV;
    private javax.swing.JTextField txtnombresV;
    private javax.swing.JTextField txtusu2;
    // End of variables declaration//GEN-END:variables
}
